"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from glob import glob


APP = ['main.py']
DATA_FILES = [
    ('static/app_icons', glob('static/app_icons/*.png'))
]
OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'LSUIElement': True,
    },
    'includes': ['rumps', 'pyyaml'],
    'iconfile': 'static/logo.icns',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
