update_interval: 10
widgets:
  - Home DNS:
    widget_type: check_dns
    name: Home DNS
    config:
      dns: 192.168.1.100
      network: Wi-Fi
  - Cloudflare DNS:
    widget_type: check_dns
    name: Cloudflare DNS
    config:
      dns: 1.1.1.1
      network: Wi-Fi